### ISSUE TITLE
Iris compability issues with Not Enough Crashes (1.0b <-> 2.0b)

### ISSUE THREAD

**Issue by eetnaviation** [KEVINIIE123/MKalamod#1]
Iris may cause stability issues with Not Enough Crashes leading to crashes and one of the mods no functioning as intended.

**Comment by KEVINIIE123** [comment]
As stated in the info this is a known issue. It doesn't interfere with the gameplay. Just click "Continue without support".

**Comment by eetnaviation** [comment]
You just told me on voice chat that Iris leading to NotEnoughCrashes (NEC) stability issues and complete game crashes is not possible?

**Comment by KEVINIIE123** [comment]
I don't know where you heard that...

**Comment by eetnaviation** [comment]
Bro I literally have an OBS recording on my PC with you telling me that.

**Comment by KEVINIIE123** [comment]
Maybe I just accidentally said that.

**Comment by eetnaviation** [comment]
No, I told it to you and you SPECIFICALLY told me that it wouldn't happen. When I assured you it did. You said it didn't

**Comment by eetnaviation** [comment]
Bro literally stop deleteing my comments and accept that there are compability issues and you denied/LIED to me that there are issues.

**Comment by KEVINIIE123** [comment]
Maybe just TRY IT THEN???

**Comment by eetnaviation** [comment]
Just immediately making a new version isn't how you throw people under the bus.
